{ config, pkgs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Shared system modules
    ../../modules/system/user.nix
    ../../modules/system/core.nix
    ../../modules/system/desktop.nix

    # Laptop doesn't import AMD module - uses integrated graphics
    # If you need laptop-specific configs (battery, power management), add them here

    # Home manager configuration
    ../../modules/home
  ];

  # Hostname
  networking.hostName = "laptop";

  # Main user configuration
  main-user = {
    enable = true;
    userName = "user";  # Change this to your username
    description = "Main User";  # Change this to your full name
    email = "your.email@example.com";  # Change this to your email
    gitName = "";  # Optional: Leave empty to use description for git
  };

  # Laptop-specific configuration can go here
}
