{ config, pkgs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Shared system modules
    ../../modules/system/core.nix
    ../../modules/system/desktop.nix

    # Laptop doesn't import AMD module - uses integrated graphics
    # If you need laptop-specific configs (battery, power management), add them here

    # Home manager configuration
    ../../modules/home
  ];

  # Hostname
  networking.hostName = "laptop";

  # Laptop-specific configuration can go here
  # For now, everything is shared in the modules
}
