{ config, pkgs, lib, ... }:

let
  # Import personal configuration (gitignored, created by setup.sh)
  # This provides backward compatibility during transition to user-preferences module
  secrets = if builtins.pathExists ./secrets.nix
    then import ./secrets.nix
    else {
      personalInfo = {
        userName = "user";
        fullName = "Main User";
        email = "your.email@example.com";
        gitName = "";
        timezone = "America/Denver";
      };
      desktopEnvironment = "plasma";  # Default desktop environment
    };
in
{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Shared system modules
    ../../modules/system/user.nix
    ../../modules/system/user-preferences.nix  # New preferences module
    ../../modules/system/core.nix
    ../../modules/system/desktop-environment.nix

    # Desktop environment modules (always imported)
    ../../modules/system/desktop/base.nix

    # Home manager configuration
    ../../modules/home
  ]
  # Conditionally import desktop-specific modules
  # During transition: reads from user-preferences which falls back to secrets.nix
  ++ lib.optionals (config.user-preferences.desktopEnvironment == "plasma") [
    ../../modules/system/desktop/plasma.nix
  ]
  ++ lib.optionals (config.user-preferences.desktopEnvironment == "hyprland") [
    ../../modules/system/desktop/hyprland.nix
  ]
  # Hardware modules
  ++ [
    ../../modules/system/hardware/nvidia.nix
  ];

  # Hostname
  networking.hostName = "desktop";

  # Configure user preferences (non-sensitive data)
  # Falls back to secrets.nix if it exists, otherwise uses defaults
  user-preferences = {
    enable = true;
    userName = secrets.personalInfo.userName;
    fullName = secrets.personalInfo.fullName;
    timezone = secrets.personalInfo.timezone;
    desktopEnvironment = secrets.desktopEnvironment or "plasma";
  };

  # Sensitive data still configured directly from secrets.nix
  # This will be migrated to agenix in a future step
  main-user = {
    email = secrets.personalInfo.email;
    gitName = secrets.personalInfo.gitName;
  };

  # Desktop-specific configuration can go here
}
