{ ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Shared system modules
    ../../modules/system/user.nix
    ../../modules/system/user-preferences.nix # New preferences module
    ../../modules/system/core.nix
    ../../modules/system/desktop-environment.nix

    # Desktop environment modules (always imported)
    ../../modules/system/desktop/base.nix
    ../../modules/system/desktop/plasma.nix
    ../../modules/system/desktop/hyprland.nix

    # Home manager configuration
    ../../modules/home

    # Hardware modules
    ../../modules/system/hardware/nvidia.nix
  ];

  # Hostname
  networking.hostName = "desktop";

  # Enable user preferences (uses defaults from user-preferences.nix)
  user-preferences.enable = true;

  # Desktop-specific configuration can go here
}
